AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-web-server specific exceptions
#
Style/CaseEquality:
  Exclude:
    - 'lib/ronin/web/server/conditions.rb'
